services:
  - type: web
    name: resqgrid-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm --workspace=packages/types run build && npm --workspace=apps/api run prisma:generate && npm --workspace=apps/api run build
    startCommand: npm --workspace=apps/api run start
    healthCheckPath: /health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: STORAGE_PROVIDER
        value: s3
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        value: resqgrid-emergency-media
      - key: LLM_PROVIDER
        value: openai
      - key: LLM_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-4o-mini
